#application-details
spring.application.name=springboot-in-vs-code
server.port=9090

#datasource
# filepath: /d:/Work_Space/Typescripts/Java-In-VS/springboot-in-vs-code/src/main/resources/application.properties
spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
# spring.datasource.platform=h2
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#log JPA queries (should comment at production)
spring.jpa.show-sql=true

# Initialize the database schema
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql

# Drop and create new tables (create, create-drop, validate, update)
# Only for testing purposes - comment this in production
spring.jpa.hibernate.ddl-auto=update

#swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
