INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (1, 'John Doe', '1985-01-15', 'Software Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (2, 'Jane Smith', '1990-02-20', 'Project Manager');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (3, 'Alice Johnson', '1988-03-25', 'Business Analyst');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (4, 'Bob Brown', '1975-04-30', 'DevOps Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (5, 'Charlie Davis', '1982-05-10', 'QA Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (6, 'Diana Evans', '1995-06-15', 'UI/UX Designer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (7, 'Ethan Harris', '1987-07-20', 'Database Administrator');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (8, 'Fiona Green', '1992-08-25', 'Product Owner');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (9, 'George Hill', '1980-09-30', 'Scrum Master');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (10, 'Hannah King', '1983-10-05', 'Technical Writer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (11, 'Ian Lewis', '1991-11-10', 'System Architect');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (12, 'Jack Martin', '1986-12-15', 'Network Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (13, 'Karen Nelson', '1979-01-20', 'Security Analyst');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (14, 'Liam OBrien', '1993-02-25', 'Mobile Developer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (15, 'Mia Parker', '1984-03-30', 'Data Scientist');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (16, 'Noah Quinn', '1989-04-05', 'Cloud Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (17, 'Olivia Roberts', '1994-05-10', 'AI Specialist');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (18, 'Paul Scott', '1981-06-15', 'Blockchain Developer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (19, 'Quinn Taylor', '1996-07-20', 'Full Stack Developer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (20, 'Rachel White', '1985-08-25', 'IT Support Specialist');