INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (1, 'John Doe', '1985-01-15', 'Software Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (2, 'Jane Smith', '1990-02-20', 'Project Manager');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (3, 'Alice Johnson', '1988-03-25', 'Business Analyst');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (4, 'Bob Brown', '1975-04-30', 'DevOps Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (5, 'Charlie Davis', '1982-05-10', 'QA Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (6, 'Diana Evans', '1995-06-15', 'UI/UX Designer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (7, 'Ethan Harris', '1987-07-20', 'Database Administrator');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (8, 'Fiona Green', '1992-08-25', 'Product Owner');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (9, 'George Hill', '1980-09-30', 'Scrum Master');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (10, 'Hannah King', '1983-10-05', 'Technical Writer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (11, 'Ian Lewis', '1991-11-10', 'System Architect');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (12, 'Jack Martin', '1986-12-15', 'Network Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (13, 'Karen Nelson', '1979-01-20', 'Security Analyst');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (14, 'Liam OBrien', '1993-02-25', 'Mobile Developer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (15, 'Mia Parker', '1984-03-30', 'Data Scientist');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (16, 'Noah Quinn', '1989-04-05', 'Cloud Engineer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (17, 'Olivia Roberts', '1994-05-10', 'AI Specialist');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (18, 'Paul Scott', '1981-06-15', 'Blockchain Developer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (19, 'Quinn Taylor', '1996-07-20', 'Full Stack Developer');
INSERT INTO worker (worker_id, full_name, date_of_birth, position) VALUES (20, 'Rachel White', '1985-08-25', 'IT Support Specialist');

-- for Engineers

INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (1, 'John Doe', 'john.doe@example.com', '123-456-7890', '123 Main St', 'Engineering', 'Software Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (2, 'Jane Smith', 'jane.smith@example.com', '123-456-7891', '456 Elm St', 'Engineering', 'Project Manager');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (3, 'Alice Johnson', 'alice.johnson@example.com', '123-456-7892', '789 Oak St', 'Engineering', 'Business Analyst');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (4, 'Bob Brown', 'bob.brown@example.com', '123-456-7893', '101 Pine St', 'Engineering', 'DevOps Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (5, 'Charlie Davis', 'charlie.davis@example.com', '123-456-7894', '202 Maple St', 'Engineering', 'QA Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (6, 'Diana Evans', 'diana.evans@example.com', '123-456-7895', '303 Birch St', 'Engineering', 'UI/UX Designer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (7, 'Ethan Harris', 'ethan.harris@example.com', '123-456-7896', '404 Cedar St', 'Engineering', 'Database Administrator');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (8, 'Fiona Green', 'fiona.green@example.com', '123-456-7897', '505 Walnut St', 'Engineering', 'Product Owner');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (9, 'George Hill', 'george.hill@example.com', '123-456-7898', '606 Chestnut St', 'Engineering', 'Scrum Master');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (10, 'Hannah King', 'hannah.king@example.com', '123-456-7899', '707 Willow St', 'Engineering', 'Technical Writer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (11, 'Ian Lewis', 'ian.lewis@example.com', '123-456-7800', '808 Spruce St', 'Engineering', 'System Architect');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (12, 'Jack Martin', 'jack.martin@example.com', '123-456-7801', '909 Fir St', 'Engineering', 'Network Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (13, 'Karen Nelson', 'karen.nelson@example.com', '123-456-7802', '1010 Redwood St', 'Engineering', 'Security Analyst');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (14, 'Liam OBrien', 'liam.obrien@example.com', '123-456-7803', '1111 Cypress St', 'Engineering', 'Mobile Developer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (15, 'Mia Parker', 'mia.parker@example.com', '123-456-7804', '1212 Palm St', 'Engineering', 'Data Scientist');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (16, 'Noah Quinn', 'noah.quinn@example.com', '123-456-7805', '1313 Magnolia St', 'Engineering', 'Cloud Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (17, 'Olivia Roberts', 'olivia.roberts@example.com', '123-456-7806', '1414 Poplar St', 'Engineering', 'AI Specialist');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (18, 'Paul Scott', 'paul.scott@example.com', '123-456-7807', '1515 Dogwood St', 'Engineering', 'Blockchain Developer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (19, 'Quinn Taylor', 'quinn.taylor@example.com', '123-456-7808', '1616 Hickory St', 'Engineering', 'Full Stack Developer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (20, 'Rachel White', 'rachel.white@example.com', '123-456-7809', '1717 Ash St', 'Engineering', 'IT Support Specialist');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (21, 'Sam Wilson', 'sam.wilson@example.com', '123-456-7810', '1818 Beech St', 'Engineering', 'Software Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (22, 'Tina Young', 'tina.young@example.com', '123-456-7811', '1919 Cedar St', 'Engineering', 'Project Manager');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (23, 'Uma Zimmerman', 'uma.zimmerman@example.com', '123-456-7812', '2020 Elm St', 'Engineering', 'Business Analyst');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (24, 'Victor Adams', 'victor.adams@example.com', '123-456-7813', '2121 Oak St', 'Engineering', 'DevOps Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (25, 'Wendy Brown', 'wendy.brown@example.com', '123-456-7814', '2222 Pine St', 'Engineering', 'QA Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (26, 'Xander Clark', 'xander.clark@example.com', '123-456-7815', '2323 Maple St', 'Engineering', 'UI/UX Designer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (27, 'Yara Davis', 'yara.davis@example.com', '123-456-7816', '2424 Birch St', 'Engineering', 'Database Administrator');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (28, 'Zane Evans', 'zane.evans@example.com', '123-456-7817', '2525 Cedar St', 'Engineering', 'Product Owner');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (29, 'Amy Foster', 'amy.foster@example.com', '123-456-7818', '2626 Walnut St', 'Engineering', 'Scrum Master');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (30, 'Brian Green', 'brian.green@example.com', '123-456-7819', '2727 Chestnut St', 'Engineering', 'Technical Writer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (31, 'Cathy Hill', 'cathy.hill@example.com', '123-456-7820', '2828 Willow St', 'Engineering', 'System Architect');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (32, 'David King', 'david.king@example.com', '123-456-7821', '2929 Spruce St', 'Engineering', 'Network Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (33, 'Eva Lewis', 'eva.lewis@example.com', '123-456-7822', '3030 Fir St', 'Engineering', 'Security Analyst');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (34, 'Frank Martin', 'frank.martin@example.com', '123-456-7823', '3131 Redwood St', 'Engineering', 'Mobile Developer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (35, 'Grace Nelson', 'grace.nelson@example.com', '123-456-7824', '3232 Cypress St', 'Engineering', 'Data Scientist');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (36, 'Henry OBrien', 'henry.obrien@example.com', '123-456-7825', '3333 Palm St', 'Engineering', 'Cloud Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (37, 'Isla Parker', 'isla.parker@example.com', '123-456-7826', '3434 Magnolia St', 'Engineering', 'AI Specialist');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (38, 'Jack Quinn', 'jack.quinn@example.com', '123-456-7827', '3535 Poplar St', 'Engineering', 'Blockchain Developer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (39, 'Kate Roberts', 'kate.roberts@example.com', '123-456-7828', '3636 Dogwood St', 'Engineering', 'Full Stack Developer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (40, 'Leo Scott', 'leo.scott@example.com', '123-456-7829', '3737 Hickory St', 'Engineering', 'IT Support Specialist');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (41, 'Mia Taylor', 'mia.taylor@example.com', '123-456-7830', '3838 Ash St', 'Engineering', 'Software Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (42, 'Nina Wilson', 'nina.wilson@example.com', '123-456-7831', '3939 Beech St', 'Engineering', 'Project Manager');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (43, 'Oscar Young', 'oscar.young@example.com', '123-456-7832', '4040 Cedar St', 'Engineering', 'Business Analyst');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (44, 'Penny Zimmerman', 'penny.zimmerman@example.com', '123-456-7833', '4141 Elm St', 'Engineering', 'DevOps Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (45, 'Quincy Adams', 'quincy.adams@example.com', '123-456-7834', '4242 Oak St', 'Engineering', 'QA Engineer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (46, 'Rita Brown', 'rita.brown@example.com', '123-456-7835', '4343 Pine St', 'Engineering', 'UI/UX Designer');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (47, 'Steve Clark', 'steve.clark@example.com', '123-456-7836', '4444 Maple St', 'Engineering', 'Database Administrator');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (48, 'Tina Davis', 'tina.davis@example.com', '123-456-7837', '4545 Birch St', 'Engineering', 'Product Owner');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (49, 'Uma Evans', 'uma.evans@example.com', '123-456-7838', '4646 Cedar St', 'Engineering', 'Scrum Master');
INSERT INTO engineer (id, name, email, phone, address, department, role) VALUES (50, 'Victor Foster', 'victor.foster@example.com', '123-456-7839', '4747 Walnut St', 'Engineering', 'Technical Writer');